In [1]:
import numpy as np  #numpy solo lee un tipo en un archivo entonces leeremos todo como string en el csv, pandas si hace esto solo

In [7]:
data = np.loadtxt('mamiferos.csv', dtype=str, delimiter = ',')

In [8]:
data

array([['animal', 'vuela', 'ponehuevos', 'nada', 'mamifero'],
       ['gallina', '0', '1', '0', '0'],
       ['perro', '0', '0', '1', '1'],
       ['gato', '0', '0', '1', '1'],
       ['pinguino', '0', '1', '1', '0'],
       ['pato', '1', '1', '1', '0'],
       ['ornitorrinco', '0', '1', '1', '1'],
       ['murcielago', '1', '0', '0', '1']], dtype='<U12')

In [11]:
data.shape #me da un array lineal

(8, 5)

In [12]:
data[0]

array(['animal', 'vuela', 'ponehuevos', 'nada', 'mamifero'], dtype='<U12')

In [34]:
features_index = {n:i for i, n in enumerate (data[0,1:])} #saco animal del feature

In [35]:
features_index

{'vuela': 0, 'ponehuevos': 1, 'nada': 2, 'mamifero': 3}

In [36]:
def column(f): return features_index[f]

In [37]:
column('vuela')

0

In [38]:
X = data[1:,1:].astype(int)

In [39]:
X

array([[0, 1, 0, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 1],
       [0, 1, 1, 0],
       [1, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 0, 1]])

In [40]:
ponehuevos = X[:,column('ponehuevos')] #deme todos de la columna ponehuevos
ponehuevos

array([1, 0, 0, 1, 1, 1, 0])

In [41]:
nada = X[:, column('nada')] 
nada

array([0, 1, 1, 1, 1, 1, 0])

In [42]:
ponehuevos & nada #and logico

array([0, 0, 0, 1, 1, 1, 0])

In [45]:
#----------APARTE -----------------
a = np.array([12,23,45])
a + 100 #numpy hace esto
#(a + a) % 2 + 1

array([112, 123, 145])

In [49]:
ponehuevos & nada == 1

array([False, False, False,  True,  True,  True, False])

In [53]:
animals = data[1:,0]
animals

array(['gallina', 'perro', 'gato', 'pinguino', 'pato', 'ornitorrinco',
       'murcielago'], dtype='<U12')

In [51]:
animals[(ponehuevos & nada == 1)]

array(['pinguino', 'pato', 'ornitorrinco'], dtype='<U12')